name: jptapp
description: JPT

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^4.0.2
  # Bloc for state management
  flutter_bloc: ^4.0.0
  # Value equality
  equatable: ^1.1.1
  # Functional programming thingies
  dartz: ^0.9.0
  # Remote API
  data_connection_checker: ^0.3.4
  #Rive animations
  flare_flutter: ^2.0.3
  #Injectable
  injectable: ^0.3.0
  #http
  http: ^0.12.1
  #User id
  uuid: ^2.0.4
  #pdf viewer
  flutter_plugin_pdf_viewer: ^1.0.7
  # Local cache
  shared_preferences: ^0.5.7
  #Firebase
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3
  #Freezed unions
  freezed_annotation: ^0.7.1
  #web viewer
  webview_flutter: ^0.3.21
  #lacalization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1
  freezed: ^0.10.7
  build_runner: ^1.9.0
  injectable_generator: ^0.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/